name: Nightly Build

on:
  push:
    branches: ["master"]

permissions:
  contents: write

jobs:
  dist:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6

      - name: Install nvim
        run: make nvim-bin

      - name: Build
        run: PREFIX=dist NVIM=nvim-linux-x86_64/bin/nvim make install

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: ${{ github.ref_name }}-dist
          publish_dir: ./dist
          force_orphan: true
          enable_jekyll: true
