name: Nightly Build

on:
  push:
    branches: ["master"]

jobs:
  NightlyBuild:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install nvim
        run: make nvim-bin

      - name: Build
        run: PREFIX=dist NVIM=nvim-linux-x86_64/bin/nvim make install

      - name: Create Tarball
        run: tar -czf nvpp.tar.gz dist/

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          name: Nvim++ Nightly
          prerelease: true
          files: nvpp.tar.gz
